name: se_daft
channels:
  - default
  - conda-forge
  - anaconda
dependencies:
- pip
- python=3.8.16
- conda-build
- cxx-compiler
- librosa=0.7.2
- numba=0.48
- numpy=1.23.0
- dask
- pynini==2.1.4
- baumwelch
- ngram
- openblas
- openfst
- pip:
  - inflect==5.3.0
  # - librosa==0.7.2
  - matplotlib == 3.4.3
  - montreal-forced-aligner == 2.0.0a24
  - python-dateutil == 2.8.2
  - tgt == 1.4.4
  - unidecode == 1.2.0
  - resampy==0.3.1
  - Pillow==9.5.0
  - setuptools==59.5.0
  - torch==1.9.0
  - torchaudio==0.9.0
  - tensorboard==2.13.0
  - jupyter
  - pyworld==0.3.3
  - pymongo[srv]==3.11.0
  - mongoengine==0.23.0
  - python-dotenv
  - streamlit==1.24.0
  - scikit-learn==1.2.2
  - scipy==1.5.0