daft_config_path: "/work/tc046/tc046/lordzuko/work/speech-editor/conf/daft_config.json"
vocoder_config_path: "/work/tc046/tc046/lordzuko/work/speech-editor/conf/vocoder_config.json"
daft_chkpt_path: "/work/tc046/tc046/lordzuko/work/speech-editor/assets/models/DaftExprt_best"
vocoder_chkpt_path: "/work/tc046/tc046/lordzuko/work/speech-editor/assets/models/g_00100000"
stats:
    phone_stats: "/work/tc046/tc046/lordzuko/work/speech-editor/assets/stats/phone_stats.json"
    global_stats: "/work/tc046/tc046/lordzuko/work/speech-editor/assets/stats/global_stats.json"
