daft_config_path: "/home/lordzuko/work/speech-editor/conf/daft_config.json"
vocoder_config_path: "/home/lordzuko/work/speech-editor/conf/vocoder_config.json"
daft_chkpt_path: "/home/lordzuko/work/speech-editor/assets/models/DaftExprt_best"
vocoder_chkpt_path: "/home/lordzuko/work/speech-editor/assets/models/g_00100000"
stats:
    phone_stats: "/home/lordzuko/work/speech-editor/assets/stats/phone_stats.json"
    global_stats: "/home/lordzuko/work/speech-editor/assets/stats/global_stats.json"
save:
    unedited: "/home/lordzuko/work/speech-editor/data/unedited"
    edited: "/home/lordzuko/work/speech-editor/data/edited"
ref_style:
    style1: "/home/lordzuko/work/speech-editor/assets/ref_style/CB-EM-04-130.wav"
    style2: "/home/lordzuko/work/speech-editor/assets/ref_style/CB-EM-09-264.wav"
    style3: "/home/lordzuko/work/speech-editor/assets/ref_style/CB-EM-26-343.wav"
    style4: "/home/lordzuko/work/speech-editor/assets/ref_style/CB-FFM-31-47.wav"
    style5: "/home/lordzuko/work/speech-editor/assets/ref_style/CB-LCL-07-57.wav"
text: 
    text1: "The minutes passed very slowly: fifteen were counted before the library- door again opened."
    text2: "She felt immediately that she should like him;"
    text3: "Gabriel, will you stay on with me?"
    text4: "I am sure, a month ago, I had no more idea myself!"